version: '3'
services:
  kicker-registry:
    image: n52/kicker-registry:latest
    build:
      dockerfile: ./Dockerfile
      context: .
      args:
        JAR_FILE: "build/libs/kicker-registry-server-0.0.1-SNAPSHOT.jar"
    volumes: 
      - ./persistence/tmp:/tmp
    ports: 
      - 8761:8761